name: .NET Test Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - develop
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui-android
 
      - name: Herstel afhankelijkheden
        run: dotnet restore
 
      - name: Bouw de applicatie
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test TestCore/TestCore.csproj -f net8.0 --configuration Release --no-restore --verbosity normal --no-build --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults
  
      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults
